### ISSUE TITLE
Problem with the information help command

### ISSUE THREAD

**Issue by ibx34** [FurryBotCo/FurryBot#53]
When running `help information` and looking at invite it will say `{lang​:commands.information.invite.description}`

![image](https://user-images.githubusercontent.com/51100404/102150838-5a52fe80-3e26-11eb-9560-bdbd152ed27e.png)
![image](https://user-images.githubusercontent.com/51100404/102150848-5fb04900-3e26-11eb-8a88-c52455650431.png)

Don't know if this was already known, just thought I'd drop in

**Comment by DonovanDMC** [comment]
I'm aware, just never got around to fixing it

**Comment by ibx34** [comment]
Makes sense. Thank you.
